# Generated by Django 4.0.4 on 2022-07-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
