# Generated by Django 4.0.4 on 2022-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_tags_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='realfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
