# Generated by Django 4.0.4 on 2022-07-15 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_article_auteur_article_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
