# Generated by Django 4.0.4 on 2022-08-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_realfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='article',
            name='urlfichier',
        ),
    ]
