# Generated by Django 4.0.4 on 2022-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_article_fichier_remove_article_urlfichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='realfile',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
    ]
