# Generated by Django 4.0.4 on 2022-07-17 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ManyToManyField(blank=True, null=True, related_name='articlelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
