# Generated by Django 4.0.4 on 2022-09-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_article_realfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nbvus',
            field=models.IntegerField(default=0),
        ),
    ]
