# Generated by Django 4.0.4 on 2022-07-21 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sauvegarde',
            field=models.ManyToManyField(blank=True, related_name='sauvegardelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
