# Generated by Django 4.0.4 on 2022-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article_nbvus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nbposts',
            field=models.IntegerField(default=0),
        ),
    ]
