# Generated by Django 4.0.4 on 2022-09-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_nbposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteurstr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
