# Generated by Django 4.0.4 on 2022-07-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_adresse_user_etablissement_user_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
