# Generated by Django 4.0.4 on 2022-09-05 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_article_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('C_Id', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=500)),
                ('comment_date', models.DateField()),
                ('comment_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentslist', to='app.article')),
            ],
        ),
    ]
