# Generated by Django 4.0.4 on 2022-07-26 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommendationlist',
            field=models.ManyToManyField(blank=True, related_name='recommendationlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
