# Generated by Django 4.0.4 on 2022-07-29 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_suivis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suivis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivislist', to=settings.AUTH_USER_MODEL),
        ),
    ]
