# Generated by Django 4.0.4 on 2022-07-29 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_suivis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUrl',
            fields=[
                ('S_Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('owner', models.ManyToManyField(blank=True, related_name='Siteslist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
