# Generated by Django 4.0.4 on 2022-07-29 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_siteurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteurl',
            name='owner',
        ),
        migrations.AddField(
            model_name='siteurl',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Siteslist', to=settings.AUTH_USER_MODEL),
        ),
    ]
