# Generated by Django 4.0.4 on 2022-07-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_siteurl_owner_siteurl_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suivisnb',
            field=models.IntegerField(default=0),
        ),
    ]
