# Generated by Django 4.0.4 on 2022-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_suivisnb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fichier',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='urlfichier',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
